-- 입양기록은 있고 보호소에 들어온 기록이 없는 동물의 ID,이름을 ID순으로 조회

SELECT 
    ANIMAL_ID, 
    O.NAME
FROM
    ANIMAL_OUTS O
LEFT JOIN 
    ANIMAL_INS I USING (ANIMAL_ID)
WHERE 
    I.DATETIME IS NULL
ORDER BY 
    ANIMAL_ID;