-- 보호기간이 가장 길었던 동물들의 아이디, 이름 조회, 보호기간(입양-보호)이 큰 순서대로
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY (DATEDIFF(O.DATETIME,I.DATETIME)) DESC
LIMIT 2