-- 아이스크림 주 성분 과일인 아이스크림의 맛 , 총 주문량 DESC
SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN ICECREAM_INFO I
ON F.FLAVOR=I.FLAVOR
WHERE I.INGREDIENT_TYPE = "fruit_based" AND F.TOTAL_ORDER > 3000
ORDER BY  F.TOTAL_ORDER DESC

