SET @max_board = (SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1);


SELECT CONCAT('/home/grep/src/', @max_board, '/', FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH 
FROM USED_GOODS_FILE
WHERE BOARD_ID = @max_board
ORDER BY FILE_ID DESC