-- 리뷰를 가장 많이 작성한 회원의 리뷰
-- 리뷰 작성일 기준 오름차순, 리뷰작성일이 같다면 리뷰 텍스트를 기준 오름차순
SELECT P.MEMBER_NAME , R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE P
    JOIN (
    SELECT REVIEW_TEXT, REVIEW_DATE, MEMBER_ID
    FROM REST_REVIEW
    WHERE MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1)
    ) R
ON R.MEMBER_ID = P.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT