-- 상품코드 별 매출액(판매가 * 판매량)합계 출력
-- 매출액 기준 내림차순 desc, asc
SELECT P.PRODUCT_CODE, SUM(P.PRICE* O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
    JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE