-- '10월에 대여를 시작', '세단'
-- 중복 없애기 
-- 자동차ID 내림차순
SELECT H.CAR_ID
FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
WHERE MONTH(DATE_FORMAT(H.START_DATE,"%Y-%m-%d")) = "10"
AND  C.CAR_TYPE ='세단'
GROUP BY C.CAR_ID
ORDER BY H.CAR_ID DESC