-- 보호시작일이 더 빠른 동물의 아이디,이름 조회( 결과는 보호 시작일 빠른 순 )
SELECT I.ANIMAL_ID , I.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID 
WHERE I.DATETIME>O.DATETIME
ORDER BY I.DATETIME ASC