-- 기존의 보호시작일보다 입양일이 더 빠른 동물의 이름과 ANIMAL_ID를 출력해라.
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID=B.ANIMAL_ID
AND A.DATETIME > B.DATETIME -- 먼저의 날짜가 더 큰 값
ORDER BY A.DATETIME ASC