-- 생일3월인 여성 ID, 이름, 성별 생년월일 (전화번호 = null : 출력대상 제외, 회원ID 오름)
SELECT MEMBER_ID, MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = "W" AND MONTH(DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d"))="3"
AND NOT TLNO IS NULL
ORDER BY MEMBER_ID ASC
